/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'USBMsg'
 * message type.
 */

public class USBMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 6;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 116;

    /** Create a new USBMsg of size 6. */
    public USBMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new USBMsg of the given data_length. */
    public USBMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new USBMsg with the given data_length
     * and base offset.
     */
    public USBMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new USBMsg using the given byte array
     * as backing store.
     */
    public USBMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new USBMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public USBMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new USBMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public USBMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new USBMsg embedded in the given message
     * at the given base offset.
     */
    public USBMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new USBMsg embedded in the given message
     * at the given base offset and length.
     */
    public USBMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <USBMsg> \n";
      try {
        s += "  [nodeID=0x"+Long.toHexString(get_nodeID())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sequence=0x"+Long.toHexString(get_sequence())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [counter=0x"+Long.toHexString(get_counter())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nodeID
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nodeID' is signed (false).
     */
    public static boolean isSigned_nodeID() {
        return false;
    }

    /**
     * Return whether the field 'nodeID' is an array (false).
     */
    public static boolean isArray_nodeID() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nodeID'
     */
    public static int offset_nodeID() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nodeID'
     */
    public static int offsetBits_nodeID() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'nodeID'
     */
    public short get_nodeID() {
        return (short)getUIntBEElement(offsetBits_nodeID(), 8);
    }

    /**
     * Set the value of the field 'nodeID'
     */
    public void set_nodeID(short value) {
        setUIntBEElement(offsetBits_nodeID(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'nodeID'
     */
    public static int size_nodeID() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nodeID'
     */
    public static int sizeBits_nodeID() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sequence
    //   Field type: long, unsigned
    //   Offset (bits): 8
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sequence' is signed (false).
     */
    public static boolean isSigned_sequence() {
        return false;
    }

    /**
     * Return whether the field 'sequence' is an array (false).
     */
    public static boolean isArray_sequence() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sequence'
     */
    public static int offset_sequence() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sequence'
     */
    public static int offsetBits_sequence() {
        return 8;
    }

    /**
     * Return the value (as a long) of the field 'sequence'
     */
    public long get_sequence() {
        return (long)getUIntBEElement(offsetBits_sequence(), 32);
    }

    /**
     * Set the value of the field 'sequence'
     */
    public void set_sequence(long value) {
        setUIntBEElement(offsetBits_sequence(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'sequence'
     */
    public static int size_sequence() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sequence'
     */
    public static int sizeBits_sequence() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: counter
    //   Field type: short, unsigned
    //   Offset (bits): 40
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'counter' is signed (false).
     */
    public static boolean isSigned_counter() {
        return false;
    }

    /**
     * Return whether the field 'counter' is an array (false).
     */
    public static boolean isArray_counter() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'counter'
     */
    public static int offset_counter() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'counter'
     */
    public static int offsetBits_counter() {
        return 40;
    }

    /**
     * Return the value (as a short) of the field 'counter'
     */
    public short get_counter() {
        return (short)getUIntBEElement(offsetBits_counter(), 8);
    }

    /**
     * Set the value of the field 'counter'
     */
    public void set_counter(short value) {
        setUIntBEElement(offsetBits_counter(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'counter'
     */
    public static int size_counter() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'counter'
     */
    public static int sizeBits_counter() {
        return 8;
    }

}
